[workspace]
resolver = "3"
members = [
    "misc/simple-motion",
    "misc/tasker",
    "misc/iceoryx-types",
    "misc/launcher",
    "misc/vesc-translator",
    "common",
    "lunabot-cu",
    "embedded_common",
    "misc/copperconfig-validator",
    "external-tasks/realsense",
    "lunabase-lib",
    "misc/quic",
    "misc/auto-start",
    "misc/wgsl-pcl", "external-tasks/device_reset", 
]
exclude = ["misc/usb-reset", "embedded", "copper-rs", "embedded-legacy", "misc/multiplexed-camera-viewer"]
# Shared dependencies across workspace members
[workspace.dependencies]
cu29 = { version = "1.2.0", features = [
    "log-level-info",
    "std",
    "log-level-error",
] }
cu29-export = { version = "1.2.0" }

cu-bincode = { version = "2.1.0", features = ["derive", "serde"] }
cu29-helpers = { version = "1.2.0" }
cu-apriltag = { git = "https://github.com/matthewashton-k/copper-rs.git", branch = "master", package = "cu-apriltag" }
# cu-consolemon = { git = "https://github.com/matthewashton-k/copper-rs.git", branch = "master", package = "cu-consolemon" }
cu-sensor-payloads = { version = "1.2.0" }
cu-spatial-payloads = { version = "1.1.1", features = [
    "nalgebra",
] }
cu29-runtime = { version = "1.2.0" }
cu-gstreamer = { version = "1.1.1", features = [
    "gst",
] }
iceoryx2 = { version = "0.8.1" }
crossbeam = "0.8"
crossbeam-channel = "0.5"


toml = "0.9.5"
bitcode = "0.6.7"
serde-big-array = "0.5.1"


nalgebra = { version = "0.34.0", features = [
    "serde-serialize",
    "convert-bytemuck",
] }

ron = { version = "0.12.0", features = ["indexmap"] }
fxhash = "0.2.1"
indexmap = "2.9.0"
tokio = { version = "1", features = ["full"] }
parking_lot = "0.12.2"
bytemuck = { version = "1", features = ["derive", "extern_crate_alloc"] }
anyhow = "1"
unfmt = "0.2.2"
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.17"


tokio-serial = "5.4.5"
tokio-util = "0.7.16"
futures-util = "0.3.31"
cobs = "0.5.1"

# members
common = { path = "common" }

# [patch."https://github.com/matthewashton-k/copper-rs.git"]
# cu29                = { path = "copper-rs/core/cu29" }
# cu29-runtime        = { path = "copper-rs/core/cu29_runtime" }
# cu29-derive         = { path = "copper-rs/core/cu29_derive" }
# cu29-helpers        = { path = "copper-rs/core/cu29_helpers" }
# cu29-export         = { path = "copper-rs/core/cu29_export" }
# cu29-traits         = { path = "copper-rs/core/cu29_traits" }
# cu29-unifiedlog     = { path = "copper-rs/core/cu29_unifiedlog" }
# cu29-log            = { path = "copper-rs/core/cu29_log" }
# cu29-log-derive     = { path = "copper-rs/core/cu29_log_derive" }
# cu29-log-runtime    = { path = "copper-rs/core/cu29_log_runtime" }
# cu29-clock          = { path = "copper-rs/core/cu29_clock" }
# cu29-value          = { path = "copper-rs/core/cu29_value" }
# cu29-intern-strs    = { path = "copper-rs/core/cu29_intern_strs" }
# cu29-base-derive    = { path = "copper-rs/core/cu29_base_derive" }
# cu29-soa-derive     = { path = "copper-rs/core/cu29_soa_derive" }
# cu-sensor-payloads  = { path = "copper-rs/components/payloads/cu_sensor_payloads" }
# cu-spatial-payloads = { path = "copper-rs/components/payloads/cu_spatial_payloads" }
# cu-apriltag         = { path = "copper-rs/components/tasks/cu_apriltag" }
# cu-gstreamer        = { path = "copper-rs/components/sources/cu_gstreamer" }

# Workspace-level metadata
[workspace.metadata]
# You can add custom metadata here if needed